#!/usr/bin/env bash

if ! [[ -n "${TWITTER_AUTH_TOKEN}" ]]; then
    echo "TWITTER_AUTH_TOKEN is not set or empty"
    exit 1
fi

cleanup() {
  docker ps -a -q --filter ancestor=diygod/rsshub | xargs -r docker rm -f
}

trap cleanup EXIT

docker run -d \
  -e TWITTER_AUTH_TOKEN=$TWITTER_AUTH_TOKEN \
  -p 1200:1200 diygod/rsshub

sleep 5

mkdir -p public/feeds

curl 'http://127.0.0.1:1200/twitter/user/elonmusk?format=json' > public/feeds/elonmusk.json

npx prettier --write public/feeds
