#!/usr/bin/env bash

if ! [[ -n "${TWITTER_AUTH_TOKEN}" ]]; then
    echo "TWITTER_AUTH_TOKEN is not set or empty"
    exit 1
fi

cleanup() {
  docker ps -a -q --filter ancestor=diygod/rsshub | xargs -r docker rm -f
}

trap cleanup EXIT

docker run -d \
  -e TWITTER_AUTH_TOKEN=$TWITTER_AUTH_TOKEN \
  -p 1200:1200 diygod/rsshub

sleep 5

mkdir -p app/public/feeds

while IFS= read -r line; do
  FEED_NAME=$(echo $line | awk -F ',' '{print $1}')
  RSS_PATH=$(echo $line | awk -F ',' '{print $2}')
  FEED_FILENAME=$(echo $line | awk -F ',' '{print $3}')

  if [[ $RSS_PATH == http* ]]; then
    echo $RSS_PATH
    curl -A "Mozilla/5.0 (compatible; MyRSSReader/1.0)" $RSS_PATH > "/tmp/$FEED_FILENAME.xml"
    xq --json "/tmp/$FEED_FILENAME.xml" > "app/public/feeds/$FEED_FILENAME.json"
  else
    echo "http://127.0.0.1:1200$RSS_PATH?format=json"
    curl "http://127.0.0.1:1200$RSS_PATH?format=json" > "app/public/feeds/$FEED_FILENAME.json"
  fi
done < configs/feeds.csv

cp configs/feeds.csv app/public/feeds
