#!/usr/bin/env bash

# 1. Check node version
scripts/node

# 2. Init agent skills
scripts/agentskills

# 3. Init shadcn vite project
npx shadcn@latest init --preset b0 --template next

# 4. Prompt opencode

# 5. TODO: Build static
