on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm --prefix app install

      - name: Run lint
        run: ./scripts/lint

      - name: Check formatting
        run: ./scripts/format check

      - name: Run typecheck
        run: ./scripts/typecheck

  test:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm --prefix app install

      - name: Install xq
        run: apt-get install xq

      - name: Run feeds
        run: ./scripts/feeds
        env:
          TWITTER_AUTH_TOKEN: ${{ secrets.TWITTER_AUTH_TOKEN }}

      - name: Build
        run: ./scripts/build

      - name: Build
        run: ./scripts/preview &

      - name: Test Feeds
        run: ./test/feeds
